
version: '3.7'

services:

  web:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    command: gunicorn mtn_django.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
      - ./app:/home/app/web
    expose:
      - 8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev.db
    environment:
      - POSTGRES_USER=mtn
      - POSTGRES_PASSWORD=mtn
      - POSTGRES_DB=mtn_dev

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume: