# Generated by Django 3.1 on 2020-08-07 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtn_web', '0002_auto_20200806_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='articles_per_country',
            field=models.JSONField(blank=True, max_length=20000, null=True),
        ),
    ]
