# Generated by Django 3.1 on 2020-08-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtn_web', '0003_auto_20200807_0602'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='country_alpha2_code',
            field=models.CharField(default='alpha2code', max_length=10),
        ),
        migrations.AddField(
            model_name='source',
            name='country_display_name',
            field=models.CharField(default='display_name_placeholder', max_length=100),
        ),
    ]
