# Generated by Django 3.1 on 2020-08-29 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtn_web', '0004_auto_20200829_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='country_alphanum_name',
            field=models.CharField(default='alphanum_name_placeholder', max_length=100),
        ),
        migrations.AddField(
            model_name='source',
            name='language_alpha2_code',
            field=models.CharField(default='alpha2code', max_length=10),
        ),
        migrations.AddField(
            model_name='source',
            name='language_alphanum_name',
            field=models.CharField(default='alphanum_name_placeholder', max_length=100),
        ),
        migrations.AddField(
            model_name='source',
            name='language_display_name',
            field=models.CharField(default='display_name_placeholder', max_length=100),
        ),
    ]
