# Generated by Django 3.1 on 2020-08-30 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtn_web', '0005_auto_20200829_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alpha2_code', models.CharField(default='--', max_length=10)),
                ('display_name', models.CharField(default='--', max_length=100)),
                ('alphanum_name', models.CharField(default='--', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alpha2_code', models.CharField(default='--', max_length=10)),
                ('display_name', models.CharField(default='--', max_length=100)),
                ('alphanum_name', models.CharField(default='--', max_length=100)),
            ],
        ),
    ]
