# Generated by Django 3.1 on 2020-09-01 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtn_web', '0008_source_readership_countries'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='languages',
            field=models.ManyToManyField(null=True, related_name='sources', to='mtn_web.Language'),
        ),
    ]
