# Generated by Django 3.1.1 on 2020-09-01 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtn_web', '0009_source_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='languages',
            field=models.ManyToManyField(related_name='sources', to='mtn_web.Language'),
        ),
    ]
