# Generated by Django 3.2.4 on 2021-06-13 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtn_web', '0011_auto_20200917_1440'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['display_name']},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['display_name']},
        ),
    ]
